version: 2

sources:
  - name: weather_data
    tables:
      - name: weather_data
  - name: prod_weather_data
    tables:
      - name: city_ref
  - name: housing
    tables:
      - name: zillow-for-sale-inventory
  - name: spotify
    tables:
      - name: streaming_history_2012_2019
      - name: streaming_history_2019_2020
      - name: streaming_history_2020_2022
      - name: streaming_history_2022_2024


