version: 2

sources:
  - name: weather_data
    tables:
      - name: weather_data
  - name: prod_weather_data
    tables:
      - name: city_ref
  - name: housing
    tables:
      - name: zillow-for-sale-inventory


