name: Run Weather Query

on:
  schedule:
    - cron: "0 9 * * *"  # Run at 9:00 AM UTC every day
    - cron: "0 17 * * *"  # Run at 5:00 PM UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create BigQuery key file
        env:
          FAITH_BQ_KEY: ${{ secrets.FAITH_BQ_KEY }}
        run: echo "$FAITH_BQ_KEY" > $GITHUB_WORKSPACE/faith_bq_key.json

      - name: Check if BigQuery key file exists
        run: ls -l $GITHUB_WORKSPACE/faith_bq_key.json

      - name: Set Weather API key
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: echo "$WEATHER_API_KEY" > weather_api_key.txt

      - name: Run Python script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/faith_bq_key.json
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python weather_query.py
