name: Run Weather Query

on:
  workflow_dispatch:  
  schedule:          
    - cron: "0 14 * * *" 
    - cron: "0 2 * * *"   

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create BigQuery key file
        env:
          FAITH_BQ_KEY: ${{ secrets.FAITH_BQ_KEY }}
        run: echo "$FAITH_BQ_KEY" > $GITHUB_WORKSPACE/faith_bq_key.json

      - name: Verify GOOGLE_APPLICATION_CREDENTIALS
        run: |
          echo "Expected path: $GITHUB_WORKSPACE/faith_bq_key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS is set to:"
          echo $GOOGLE_APPLICATION_CREDENTIALS
          echo "Checking if the file exists in workspace:"
          ls -l $GITHUB_WORKSPACE
          echo "Checking if the file exists at GOOGLE_APPLICATION_CREDENTIALS path:"
          ls -l $GOOGLE_APPLICATION_CREDENTIALS || echo "File not found!"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/faith_bq_key.json

      - name: Validate JSON format
        run: |
          echo "Validating JSON format..."
          cat $GOOGLE_APPLICATION_CREDENTIALS | jq . || echo "Invalid JSON!"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/faith_bq_key.json




