name: Run Weather Query

on:
  schedule:
    - cron: "0 9 * * *"  # Run at 9:00 AM UTC every day
    - cron: "0 17 * * *" # Run at 5:00 PM UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Python script
        run: python weather_query.py
